codecrafters-io/build-your-own-grep

compiled_starters/grep-starter-python/app/main.py, solutions/python/init/code/app/main.py, solutions/python/init/diff/app/main.py.diff, solutions/python/init/explanation.md, solutions/python/match_digit/code/.gitignore, solutions/python/match_digit/code/Pipfile, solutions/python/match_digit/code/Pipfile.lock, solutions/python/match_digit/code/README.md, solutions/python/match_digit/code/app/main.py, solutions/python/match_digit/code/codecrafters.yml, solutions/python/match_digit/code/your_grep.sh, solutions/python/match_digit/definition.yml, solutions/python/match_digit/diff/app/main.py.diff, starter_templates/python/app/main.py
- fix python starter code
- add exit(1) for unhandled pattern
- update first stage
=> Update starter code, add stage 2 solution

compiled_starters/grep-starter-python/app/main.py, course-definition.yml, solutions/python/combining_character_classes/code/.gitignore, solutions/python/combining_character_classes/code/Pipfile, solutions/python/combining_character_classes/code/Pipfile.lock, solutions/python/combining_character_classes/code/README.md, solutions/python/combining_character_classes/code/app/main.py, solutions/python/combining_character_classes/code/codecrafters.yml, solutions/python/combining_character_classes/code/your_grep.sh, solutions/python/combining_character_classes/definition.yml, solutions/python/combining_character_classes/diff/app/main.py.diff, solutions/python/init/code/app/main.py, solutions/python/init/diff/app/main.py.diff, solutions/python/match_alphanumeric/code/app/main.py, solutions/python/match_alphanumeric/diff/app/main.py.diff, solutions/python/match_digit/code/app/main.py, solutions/python/match_digit/diff/app/main.py.diff, solutions/python/negative_character_groups/code/app/main.py, solutions/python/negative_character_groups/diff/app/main.py.diff, solutions/python/positive_character_groups/code/app/main.py, solutions/python/positive_character_groups/diff/app/main.py.diff, starter_templates/python/app/main.py
- add more solutions
- add solutions for next stage
- compile stage 1
=> Add solutions till stage 6

compiled_starters/grep-starter-rust/Cargo.toml, solutions/rust/init/code/Cargo.toml, starter_templates/rust/Cargo.toml
=> update Rust edition

solutions/go/combining_character_classes/code/README.md, solutions/go/combining_character_classes/code/cmd/mygrep/main.go, solutions/go/combining_character_classes/code/codecrafters.yml, solutions/go/combining_character_classes/code/go.mod, solutions/go/combining_character_classes/code/your_grep.sh, solutions/go/combining_character_classes/diff/cmd/mygrep/main.go.diff
Huge change here.
I've made PR against first_stages branch to make diff smaller. We should merge first_stages first, then change base branch here and merge that.
=> Go: combining character classes

solutions/go/07-start_of_string_anchor/code/README.md, solutions/go/07-start_of_string_anchor/code/cmd/mygrep/main.go, solutions/go/07-start_of_string_anchor/code/codecrafters.yml, solutions/go/07-start_of_string_anchor/code/go.mod, solutions/go/07-start_of_string_anchor/code/your_grep.sh, solutions/go/07-start_of_string_anchor/diff/cmd/mygrep/main.go.diff, solutions/go/08-end_of_string_anchor/code/README.md, solutions/go/08-end_of_string_anchor/code/cmd/mygrep/main.go, solutions/go/08-end_of_string_anchor/code/codecrafters.yml, solutions/go/08-end_of_string_anchor/code/go.mod, solutions/go/08-end_of_string_anchor/code/your_grep.sh, solutions/go/08-end_of_string_anchor/diff/cmd/mygrep/main.go.diff
This is much more convenient to navigate stages starting with its number )
=> start and end of string stages

compiled_starters/grep-starter-ruby/README.md, compiled_starters/grep-starter-ruby/app/main.rb, compiled_starters/grep-starter-ruby/codecrafters.yml, compiled_starters/grep-starter-ruby/your_grep.sh, dockerfiles/ruby-2.7.Dockerfile, solutions/ruby/01-init/code/README.md, solutions/ruby/01-init/code/app/main.rb, solutions/ruby/01-init/code/codecrafters.yml, solutions/ruby/01-init/code/your_grep.sh, solutions/ruby/01-init/diff/app/main.rb.diff, solutions/ruby/01-init/explanation.md, starter-repository-definitions.yml, starter_templates/ruby/app/main.rb, starter_templates/ruby/your_grep.sh
@rohitpaulk The following PR adds ruby support for Build your own grep. I've added the started code for passing the first stage. `compile_and_test.sh` is passing locally.
=> Add ruby support

dockerfiles/cpp-23.Dockerfile, dockerfiles/dotnet-8.0.Dockerfile, dockerfiles/gleam-1.0.Dockerfile, dockerfiles/haskell-9.2.Dockerfile, dockerfiles/rust-1.62.Dockerfile, dockerfiles/rust-1.68.Dockerfile, dockerfiles/rust-1.70.Dockerfile, dockerfiles/rust-1.76.Dockerfile, dockerfiles/rust-1.77.Dockerfile
=> replace-submission-dir

compiled_starters/rust/.codecrafters/compile.sh, compiled_starters/rust/.codecrafters/run.sh, compiled_starters/rust/Cargo.lock, compiled_starters/rust/Cargo.toml, compiled_starters/rust/README.md, compiled_starters/rust/codecrafters.yml, compiled_starters/rust/your_program.sh, dockerfiles/rust-1.80.Dockerfile, solutions/rust/01-cq2/code/.codecrafters/compile.sh, solutions/rust/01-cq2/code/.codecrafters/run.sh, solutions/rust/01-cq2/code/Cargo.lock, solutions/rust/01-cq2/code/Cargo.toml, solutions/rust/01-cq2/code/README.md, solutions/rust/01-cq2/code/codecrafters.yml, solutions/rust/01-cq2/code/your_program.sh, starter_templates/rust/code/.codecrafters/compile.sh, starter_templates/rust/code/.codecrafters/run.sh, starter_templates/rust/code/Cargo.lock, starter_templates/rust/code/Cargo.toml, starter_templates/rust/config.yml
=> Upgrade Rust

compiled_starters/rust/Cargo.lock, solutions/rust/01-cq2/code/Cargo.lock, starter_templates/rust/code/Cargo.lock
=> Upgrade Rust dep versions

compiled_starters/cpp/README.md, compiled_starters/csharp/README.md, compiled_starters/gleam/README.md, compiled_starters/go/README.md, compiled_starters/haskell/README.md, compiled_starters/javascript/README.md, compiled_starters/kotlin/README.md, compiled_starters/python/README.md, compiled_starters/ruby/README.md, compiled_starters/rust/README.md, compiled_starters/typescript/README.md, solutions/cpp/01-cq2/code/README.md, solutions/csharp/01-cq2/code/README.md, solutions/gleam/01-cq2/code/README.md, solutions/go/01-cq2/code/README.md, solutions/haskell/01-cq2/code/README.md, solutions/javascript/01-cq2/code/README.md, solutions/kotlin/01-cq2/code/README.md, solutions/python/01-cq2/code/README.md, solutions/ruby/01-cq2/code/README.md, solutions/rust/01-cq2/code/README.md, solutions/typescript/01-cq2/code/README.md, starter_templates/all/code/README.md
=> Update git add step

compiled_starters/go/cmd/mygrep/main.go, solutions/go/01-cq2/code/cmd/mygrep/main.go, solutions/go/01-cq2/diff/cmd/mygrep/main.go.diff, solutions/go/01-cq2/explanation.md, starter_templates/go/code/cmd/mygrep/main.go
- update uncomment usage
- update uncomment usage
=> fix double uncomment

compiled_starters/rust/README.md, compiled_starters/rust/codecrafters.yml, dockerfiles/rust-1.82.Dockerfile, solutions/rust/01-cq2/code/README.md, solutions/rust/01-cq2/code/codecrafters.yml, starter_templates/rust/config.yml
=> Upgrade Rust to 1.82

compiled_starters/go/go.mod, compiled_starters/haskell/package.yaml, compiled_starters/haskell/stack.yaml, compiled_starters/python/Pipfile, solutions/go/01-cq2/code/go.mod, solutions/haskell/01-cq2/code/package.yaml, solutions/haskell/01-cq2/code/stack.yaml, solutions/python/01-cq2/code/Pipfile, starter_templates/go/code/go.mod, starter_templates/haskell/code/package.yaml, starter_templates/haskell/code/stack.yaml, starter_templates/python/code/Pipfile
remove DON'T EDIT banners + empty lines and stuff
=> remove DON'T EDIT banners + empty lines and stuff

compiled_starters/gleam/.codecrafters/run.sh, compiled_starters/gleam/README.md, compiled_starters/gleam/codecrafters.yml, compiled_starters/gleam/your_program.sh, dockerfiles/gleam-1.11.Dockerfile, solutions/gleam/01-cq2/code/.codecrafters/run.sh, solutions/gleam/01-cq2/code/README.md, solutions/gleam/01-cq2/code/codecrafters.yml, solutions/gleam/01-cq2/code/your_program.sh, starter_templates/gleam/code/.codecrafters/run.sh, starter_templates/gleam/config.yml
=> Upgrade Gleam to 1.91

compiled_starters/rust/README.md, compiled_starters/rust/codecrafters.yml, dockerfiles/rust-1.87.Dockerfile, solutions/rust/01-cq2/code/README.md, solutions/rust/01-cq2/code/codecrafters.yml, starter_templates/rust/config.yml
=> Upgrade Rust to 1.87

compiled_starters/java/.codecrafters/compile.sh, compiled_starters/java/codecrafters.yml, compiled_starters/java/your_program.sh, dockerfiles/java-24.Dockerfile, solutions/java/01-cq2/code/.codecrafters/compile.sh, solutions/java/01-cq2/code/codecrafters.yml, solutions/java/01-cq2/code/your_program.sh, starter_templates/java/code/.codecrafters/compile.sh
=> Upgrade Java to 24

compiled_starters/rust/codecrafters.yml, dockerfiles/rust-1.88.Dockerfile, solutions/rust/01-cq2/code/codecrafters.yml
=> Upgrade Rust to 1.88

course-definition.yml, stage_descriptions/filesearch_1_dr5.md, stage_descriptions/filesearch_2_ol9.md, stage_descriptions/filesearch_3_is6.md, stage_descriptions/filesearch_4_yx6.md
Introduced a new stage for searching files recursively in a directory and its subdirectories using the `-r` flag. This stage includes detailed descriptions, example usage, and tests to validate functionality.
=> File-search

stage_descriptions/base-05-rk3.md
=> Update instructions #rk3 Negative Character Groups 

course-definition.yml, stage_descriptions/base-02-oq2.md, stage_descriptions/base-03-mr9.md
Context:
https://secure.helpscout.net/conversation/3033391606/9249#thread-9234252720
=> Update instructions #mr9 alphanumeric/word
